import { Stock } from '../types/Stock';

export const stockSymbols = [
  "AAPL", "MSFT", "GOOGL", "AMZN", "NVDA", "META", "TSLA", "AVGO", 
  "PEP", "CMCSA", "COST", "ADBE", "CSCO", "TMUS", "QCOM", "TXN", 
  "AMD", "INTC", "AMAT", "NFLX", "PDD", "HON", "INTU", "MRNA", 
  "AMGN", "PYPL", "VRTX", "SBUX", "MDLZ", "ISRG", "ADI", "BKNG", 
  "GILD", "REGN", "LRCX", "KLAC", "ADP", "CSX", "MELI", "SNPS", 
  "PANW", "ATVI", "XEL", "WDAY", "AEP", "CTSH", "CHTR", "IDXX", 
  "CRWD", "CDNS", "NXPI", "MRVL", "EBAY", "MNST", "ORLY", "TEAM", 
  "FTNT", "ABNB", "ODFL", "EXC", "ZS", "LCID", "ROST", "PCAR", 
  "CTAS", "SWKS", "BIIB", "PAYC", "ALGN", "KDP", "SPLK", "MTCH", 
  "DXCM", "SGEN", "FAST", "WBA", "VRSK", "MAR", "ILMN", "TTWO", 
  "ASML", "CROX", "EXPE", "CPRT", "U", "SEDG", "TSCO", "CHKP", 
  "DDOG", "FANG", "HUBS", "ZBRA", "MCHP", "DOCU", "APP", "PTON", 
  "NVCR", "TRMB", "IRDM"
];

export const stocks: Stock[] = [
  { symbol: 'AAPL', name: 'Apple Inc.', price: 150.25, change: 2.5 },
  { symbol: 'GOOGL', name: 'Alphabet Inc.', price: 2750.80, change: -1.2 },
  { symbol: 'MSFT', name: 'Microsoft Corporation', price: 305.15, change: 0.8 },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', price: 3380.50, change: 1.5 },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', price: 200.25, change: 0.5 },
  { symbol: 'META', name: 'Meta Platforms Inc.', price: 340.25, change: 0.5 },
  { symbol: 'TSLA', name: 'Tesla Inc.', price: 700.25, change: 0.5 },
  { symbol: 'AVGO', name: 'Broadcom Inc.', price: 500.25, change: 0.5 },
  { symbol: 'PEP', name: 'PepsiCo Inc.', price: 150.25, change: 0.5 },
  { symbol: 'CMCSA', name: 'Comcast Corporation', price: 50.25, change: 0.5 },
  { symbol: 'COST', name: 'Costco Wholesale Corporation', price: 500.25, change: 0.5 },
  { symbol: 'ADBE', name: 'Adobe Inc.', price: 300.25, change: 0.5 },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.', price: 50.25, change: 0.5 },
  { symbol: 'TMUS', name: 'T-Mobile US Inc.', price: 100.25, change: 0.5 },
  { symbol: 'QCOM', name: 'QUALCOMM Incorporated', price: 150.25, change: 0.5 },
  { symbol: 'TXN', name: 'Texas Instruments Incorporated', price: 150.25, change: 0.5 },
  { symbol: 'AMD', name: 'Advanced Micro Devices Inc.', price: 150.25, change: 0.5 },
  { symbol: 'INTC', name: 'Intel Corporation', price: 150.25, change: 0.5 },
  { symbol: 'AMAT', name: 'Applied Materials Inc.', price: 150.25, change: 0.5 },
  { symbol: 'NFLX', name: 'Netflix Inc.', price: 150.25, change: 0.5 },
  { symbol: 'PDD', name: 'Pinduoduo Inc.', price: 150.25, change: 0.5 },
  { symbol: 'HON', name: 'Honeywell International Inc.', price: 150.25, change: 0.5 },
  { symbol: 'INTU', name: 'Intuit Inc.', price: 150.25, change: 0.5 },
  { symbol: 'MRNA', name: 'Moderna Inc.', price: 150.25, change: 0.5 },
  { symbol: 'AMGN', name: 'Amgen Inc.', price: 150.25, change: 0.5 },
  { symbol: 'PYPL', name: 'PayPal Holdings Inc.', price: 150.25, change: 0.5 },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals Incorporated', price: 150.25, change: 0.5 },
  { symbol: 'SBUX', name: 'Starbucks Corporation', price: 150.25, change: 0.5 },
  { symbol: 'MDLZ', name: 'Mondelez International Inc.', price: 150.25, change: 0.5 },
  { symbol: 'ISRG', name: 'Intuitive Surgical Inc.', price: 150.25, change: 0.5 },
  { symbol: 'ADI', name: 'Analog Devices Inc.', price: 150.25, change: 0.5 },
  { symbol: 'BKNG', name: 'Booking Holdings Inc.', price: 150.25, change: 0.5 },
  { symbol: 'GILD', name: 'Gilead Sciences Inc.', price: 150.25, change: 0.5 },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals Inc.', price: 150.25, change: 0.5 },
  { symbol: 'LRCX', name: 'Lam Research Corporation', price: 150.25, change: 0.5 },
  { symbol: 'KLAC', name: 'KLA Corporation', price: 150.25, change: 0.5 },
  { symbol: 'ADP', name: 'Automatic Data Processing Inc.', price: 150.25, change: 0.5 },
  { symbol: 'CSX', name: 'CSX Corporation', price: 150.25, change: 0.5 },
  { symbol: 'MELI', name: 'MercadoLibre Inc.', price: 150.25, change: 0.5 },
  { symbol: 'SNPS', name: 'Synopsys Inc.', price: 150.25, change: 0.5 },
  { symbol: 'PANW', name: 'Palo Alto Networks Inc.', price: 150.25, change: 0.5 },
  { symbol: 'ATVI', name: 'Activision Blizzard Inc.', price: 150.25, change: 0.5 },
  { symbol: 'XEL', name: 'Xcel Energy Inc.', price: 150.25, change: 0.5 },
  { symbol: 'WDAY', name: 'Workday Inc.', price: 150.25, change: 0.5 },
  { symbol: 'AEP', name: 'American Electric Power Company Inc.', price: 150.25, change: 0.5 },
  { symbol: 'CTSH', name: 'Cognizant Technology Solutions Corporation', price: 150.25, change: 0.5 },
  { symbol: 'CHTR', name: 'Charter Communications Inc.', price: 150.25, change: 0.5 },
  { symbol: 'IDXX', name: 'IDEXX Laboratories Inc.', price: 150.25, change: 0.5 },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings Inc.', price: 150.25, change: 0.5 },
  { symbol: 'CDNS', name: 'Cadence Design Systems Inc.', price: 150.25, change: 0.5 },
  { symbol: 'NXPI', name: 'NXP Semiconductors N.V.', price: 150.25, change: 0.5 },
  { symbol: 'MRVL', name: 'Marvell Technology Inc.', price: 150.25, change: 0.5 },
  { symbol: 'EBAY', name: 'eBay Inc.', price: 150.25, change: 0.5 },
  { symbol: 'MNST', name: 'Monster Beverage Corporation', price: 150.25, change: 0.5 },
  { symbol: 'ORLY', name: 'O\'Reilly Automotive Inc.', price: 150.25, change: 0.5 },
  { symbol: 'TEAM', name: 'Atlassian Corporation Plc', price: 150.25, change: 0.5 },
  { symbol: 'FTNT', name: 'Fortinet Inc.', price: 150.25, change: 0.5 },
  { symbol: 'ABNB', name: 'Airbnb Inc.', price: 150.25, change: 0.5 },
  { symbol: 'ODFL', name: 'Old Dominion Freight Line Inc.', price: 150.25, change: 0.5 },
  { symbol: 'EXC', name: 'Exelon Corporation', price: 150.25, change: 0.5 },
]
