import { Stock } from '../types/Stock';

export const stocks: Stock[] = [
  { symbol: 'AAPL', name: 'Apple Inc.', price: 0, change: 0 },
  { symbol: 'GOOGL', name: 'Alphabet Inc.', price: 0, change: -0 },
  { symbol: 'MSFT', name: 'Microsoft Corporation', price: 0, change: 0 },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', price: 0, change: 0 },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', price: 0, change: 0 },
  { symbol: 'META', name: 'Meta Platforms Inc.', price: 0, change: 0 },
  { symbol: 'TSLA', name: 'Tesla Inc.', price: 0, change: 0 },
  { symbol: 'AVGO', name: 'Broadcom Inc.', price: 0, change: 0 },
  { symbol: 'PEP', name: 'PepsiCo Inc.', price: 0, change: 0 },
  { symbol: 'CMCSA', name: 'Comcast Corporation', price: 0, change: 0 },
  { symbol: 'COST', name: 'Costco Wholesale Corporation', price: 0, change: 0 },
  { symbol: 'ADBE', name: 'Adobe Inc.', price: 0, change: 0 },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.', price: 0, change: 0 },
  { symbol: 'TMUS', name: 'T-Mobile US Inc.', price: 0, change: 0 },
  { symbol: 'QCOM', name: 'QUALCOMM Incorporated', price: 0, change: 0 },
  { symbol: 'TXN', name: 'Texas Instruments Incorporated', price: 0, change: 0 },
  { symbol: 'AMD', name: 'Advanced Micro Devices Inc.', price: 0, change: 0 },
  { symbol: 'INTC', name: 'Intel Corporation', price: 0, change: 0 },
  { symbol: 'AMAT', name: 'Applied Materials Inc.', price: 0, change: 0 },
  { symbol: 'NFLX', name: 'Netflix Inc.', price: 0, change: 0 },
  { symbol: 'PDD', name: 'Pinduoduo Inc.', price: 0, change: 0 },
  { symbol: 'HON', name: 'Honeywell International Inc.', price: 0, change: 0 },
  { symbol: 'INTU', name: 'Intuit Inc.', price: 0, change: 0 },
  { symbol: 'MRNA', name: 'Moderna Inc.', price: 0, change: 0 },
  { symbol: 'AMGN', name: 'Amgen Inc.', price: 0, change: 0 },
  { symbol: 'PYPL', name: 'PayPal Holdings Inc.', price: 0, change: 0 },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals Incorporated', price: 0, change: 0 },
  { symbol: 'SBUX', name: 'Starbucks Corporation', price: 0, change: 0 },
  { symbol: 'MDLZ', name: 'Mondelez International Inc.', price: 0, change: 0 },
  { symbol: 'ISRG', name: 'Intuitive Surgical Inc.', price: 0, change: 0 },
  { symbol: 'ADI', name: 'Analog Devices Inc.', price: 0, change: 0 },
  { symbol: 'BKNG', name: 'Booking Holdings Inc.', price: 0, change: 0 },
  { symbol: 'GILD', name: 'Gilead Sciences Inc.', price: 0, change: 0 },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals Inc.', price: 0, change: 0 },
  { symbol: 'LRCX', name: 'Lam Research Corporation', price: 0, change: 0 },
  { symbol: 'KLAC', name: 'KLA Corporation', price: 0, change: 0 },
  { symbol: 'ADP', name: 'Automatic Data Processing Inc.', price: 0, change: 0 },
  { symbol: 'CSX', name: 'CSX Corporation', price: 0, change: 0 },
  { symbol: 'MELI', name: 'MercadoLibre Inc.', price: 0, change: 0 },
  { symbol: 'SNPS', name: 'Synopsys Inc.', price: 0, change: 0 },
  { symbol: 'PANW', name: 'Palo Alto Networks Inc.', price: 0, change: 0 },
  { symbol: 'ATVI', name: 'Activision Blizzard Inc.', price: 0, change: 0 },
  { symbol: 'XEL', name: 'Xcel Energy Inc.', price: 0, change: 0 },
  { symbol: 'WDAY', name: 'Workday Inc.', price: 0, change: 0 },
  { symbol: 'AEP', name: 'American Electric Power Company Inc.', price: 0, change: 0 },
  { symbol: 'CTSH', name: 'Cognizant Technology Solutions Corporation', price: 0, change: 0 },
  { symbol: 'CHTR', name: 'Charter Communications Inc.', price: 0, change: 0 },
  { symbol: 'IDXX', name: 'IDEXX Laboratories Inc.', price: 0, change: 0 },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings Inc.', price: 0, change: 0 },
  { symbol: 'CDNS', name: 'Cadence Design Systems Inc.', price: 0, change: 0 },
  { symbol: 'NXPI', name: 'NXP Semiconductors N.V.', price: 0, change: 0 },
  { symbol: 'MRVL', name: 'Marvell Technology Inc.', price: 0, change: 0 },
  { symbol: 'EBAY', name: 'eBay Inc.', price: 0, change: 0 },
  { symbol: 'MNST', name: 'Monster Beverage Corporation', price: 0, change: 0 },
  { symbol: 'ORLY', name: 'O\'Reilly Automotive Inc.', price: 0, change: 0 },
  { symbol: 'TEAM', name: 'Atlassian Corporation Plc', price: 0, change: 0 },
  { symbol: 'FTNT', name: 'Fortinet Inc.', price: 0, change: 0 },
  { symbol: 'ABNB', name: 'Airbnb Inc.', price: 0, change: 0 },
  { symbol: 'ODFL', name: 'Old Dominion Freight Line Inc.', price: 0, change: 0 },
  { symbol: 'EXC', name: 'Exelon Corporation', price: 0, change: 0 },
]

export const stockSymbols = stocks.map(stock => stock.symbol);
